// Generated by gencpp from file game_ctrl/TeamInfo.msg
// DO NOT EDIT!


#ifndef GAME_CTRL_MESSAGE_TEAMINFO_H
#define GAME_CTRL_MESSAGE_TEAMINFO_H

#include <ros/service_traits.h>


#include <game_ctrl/TeamInfoRequest.h>
#include <game_ctrl/TeamInfoResponse.h>


namespace game_ctrl
{

struct TeamInfo
{

typedef TeamInfoRequest Request;
typedef TeamInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TeamInfo
} // namespace game_ctrl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::game_ctrl::TeamInfo > {
  static const char* value()
  {
    return "967db2d47319aba09eabb132f932430e";
  }

  static const char* value(const ::game_ctrl::TeamInfo&) { return value(); }
};

template<>
struct DataType< ::game_ctrl::TeamInfo > {
  static const char* value()
  {
    return "game_ctrl/TeamInfo";
  }

  static const char* value(const ::game_ctrl::TeamInfo&) { return value(); }
};


// service_traits::MD5Sum< ::game_ctrl::TeamInfoRequest> should match 
// service_traits::MD5Sum< ::game_ctrl::TeamInfo > 
template<>
struct MD5Sum< ::game_ctrl::TeamInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::game_ctrl::TeamInfo >::value();
  }
  static const char* value(const ::game_ctrl::TeamInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::game_ctrl::TeamInfoRequest> should match 
// service_traits::DataType< ::game_ctrl::TeamInfo > 
template<>
struct DataType< ::game_ctrl::TeamInfoRequest>
{
  static const char* value()
  {
    return DataType< ::game_ctrl::TeamInfo >::value();
  }
  static const char* value(const ::game_ctrl::TeamInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::game_ctrl::TeamInfoResponse> should match 
// service_traits::MD5Sum< ::game_ctrl::TeamInfo > 
template<>
struct MD5Sum< ::game_ctrl::TeamInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::game_ctrl::TeamInfo >::value();
  }
  static const char* value(const ::game_ctrl::TeamInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::game_ctrl::TeamInfoResponse> should match 
// service_traits::DataType< ::game_ctrl::TeamInfo > 
template<>
struct DataType< ::game_ctrl::TeamInfoResponse>
{
  static const char* value()
  {
    return DataType< ::game_ctrl::TeamInfo >::value();
  }
  static const char* value(const ::game_ctrl::TeamInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAME_CTRL_MESSAGE_TEAMINFO_H
