// Generated by gencpp from file game_ctrl/TeamInfoResponse.msg
// DO NOT EDIT!


#ifndef GAME_CTRL_MESSAGE_TEAMINFORESPONSE_H
#define GAME_CTRL_MESSAGE_TEAMINFORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace game_ctrl
{
template <class ContainerAllocator>
struct TeamInfoResponse_
{
  typedef TeamInfoResponse_<ContainerAllocator> Type;

  TeamInfoResponse_()
    : team()  {
    }
  TeamInfoResponse_(const ContainerAllocator& _alloc)
    : team(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _team_type;
  _team_type team;





  typedef boost::shared_ptr< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TeamInfoResponse_

typedef ::game_ctrl::TeamInfoResponse_<std::allocator<void> > TeamInfoResponse;

typedef boost::shared_ptr< ::game_ctrl::TeamInfoResponse > TeamInfoResponsePtr;
typedef boost::shared_ptr< ::game_ctrl::TeamInfoResponse const> TeamInfoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::game_ctrl::TeamInfoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace game_ctrl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'game_ctrl': ['/home/molguitianzn/my_git/SEURoboCup2019/src/game_ctrl/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ea91258faa2e43cced50cc90a49ffff";
  }

  static const char* value(const ::game_ctrl::TeamInfoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ea91258faa2e43cULL;
  static const uint64_t static_value2 = 0xced50cc90a49ffffULL;
};

template<class ContainerAllocator>
struct DataType< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "game_ctrl/TeamInfoResponse";
  }

  static const char* value(const ::game_ctrl::TeamInfoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string team\n\
";
  }

  static const char* value(const ::game_ctrl::TeamInfoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.team);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TeamInfoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::game_ctrl::TeamInfoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::game_ctrl::TeamInfoResponse_<ContainerAllocator>& v)
  {
    s << indent << "team: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.team);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAME_CTRL_MESSAGE_TEAMINFORESPONSE_H
