// Generated by gencpp from file simulation/ImageInfo.msg
// DO NOT EDIT!


#ifndef SIMULATION_MESSAGE_IMAGEINFO_H
#define SIMULATION_MESSAGE_IMAGEINFO_H

#include <ros/service_traits.h>


#include <simulation/ImageInfoRequest.h>
#include <simulation/ImageInfoResponse.h>


namespace simulation
{

struct ImageInfo
{

typedef ImageInfoRequest Request;
typedef ImageInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageInfo
} // namespace simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simulation::ImageInfo > {
  static const char* value()
  {
    return "5fc79a3dc52bfd27e58236ef10f8fb6f";
  }

  static const char* value(const ::simulation::ImageInfo&) { return value(); }
};

template<>
struct DataType< ::simulation::ImageInfo > {
  static const char* value()
  {
    return "simulation/ImageInfo";
  }

  static const char* value(const ::simulation::ImageInfo&) { return value(); }
};


// service_traits::MD5Sum< ::simulation::ImageInfoRequest> should match 
// service_traits::MD5Sum< ::simulation::ImageInfo > 
template<>
struct MD5Sum< ::simulation::ImageInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simulation::ImageInfo >::value();
  }
  static const char* value(const ::simulation::ImageInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation::ImageInfoRequest> should match 
// service_traits::DataType< ::simulation::ImageInfo > 
template<>
struct DataType< ::simulation::ImageInfoRequest>
{
  static const char* value()
  {
    return DataType< ::simulation::ImageInfo >::value();
  }
  static const char* value(const ::simulation::ImageInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simulation::ImageInfoResponse> should match 
// service_traits::MD5Sum< ::simulation::ImageInfo > 
template<>
struct MD5Sum< ::simulation::ImageInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simulation::ImageInfo >::value();
  }
  static const char* value(const ::simulation::ImageInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation::ImageInfoResponse> should match 
// service_traits::DataType< ::simulation::ImageInfo > 
template<>
struct DataType< ::simulation::ImageInfoResponse>
{
  static const char* value()
  {
    return DataType< ::simulation::ImageInfo >::value();
  }
  static const char* value(const ::simulation::ImageInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMULATION_MESSAGE_IMAGEINFO_H
