// Generated by gencpp from file simulation/Stand.msg
// DO NOT EDIT!


#ifndef SIMULATION_MESSAGE_STAND_H
#define SIMULATION_MESSAGE_STAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulation
{
template <class ContainerAllocator>
struct Stand_
{
  typedef Stand_<ContainerAllocator> Type;

  Stand_()
    : red(false)
    , blue(false)  {
    }
  Stand_(const ContainerAllocator& _alloc)
    : red(false)
    , blue(false)  {
  (void)_alloc;
    }



   typedef uint8_t _red_type;
  _red_type red;

   typedef uint8_t _blue_type;
  _blue_type blue;





  typedef boost::shared_ptr< ::simulation::Stand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulation::Stand_<ContainerAllocator> const> ConstPtr;

}; // struct Stand_

typedef ::simulation::Stand_<std::allocator<void> > Stand;

typedef boost::shared_ptr< ::simulation::Stand > StandPtr;
typedef boost::shared_ptr< ::simulation::Stand const> StandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulation::Stand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulation::Stand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'simulation': ['/home/molguitianzn/my_git/SEURoboCup2019/src/simulation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulation::Stand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulation::Stand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulation::Stand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulation::Stand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulation::Stand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulation::Stand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulation::Stand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86ceb06532353ac324c209f78172bff1";
  }

  static const char* value(const ::simulation::Stand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86ceb06532353ac3ULL;
  static const uint64_t static_value2 = 0x24c209f78172bff1ULL;
};

template<class ContainerAllocator>
struct DataType< ::simulation::Stand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulation/Stand";
  }

  static const char* value(const ::simulation::Stand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulation::Stand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool red\n\
bool blue\n\
";
  }

  static const char* value(const ::simulation::Stand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulation::Stand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.red);
      stream.next(m.blue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Stand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulation::Stand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulation::Stand_<ContainerAllocator>& v)
  {
    s << indent << "red: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.red);
    s << indent << "blue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATION_MESSAGE_STAND_H
